default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: pzoid_development

test:
  <<: *default
  database: pzoid_test

production:
  <<: *default
  database: pzoid_production
  # username: pzoid
  # password: <%= ENV['PZOID_DATABASE_PASSWORD'] %>
